### PR TITLE
When retry to make a request pass new token

### PR DESCRIPTION
**Pull request by artjomjuferov**

### CODE REVIEW

**Comment by artjomjuferov** [comment]
Locally all specs are green.

**Comment by artjomjuferov** [comment]
https://github.com/guilhermesad/rspotify/issues/119
https://github.com/guilhermesad/rspotify/issues/115

**Comment by guilhermesad** [comment]
Nice, thanks 👍

**Comment by artjomjuferov** [comment]
Hmm, quite strange. Did you receive such exception before?

**Comment by jblauer60** [comment]
No, and I can disable it by wrapping the patch as follows (although this probably isn't the best solution):

          unless caller[1].end_with? "oauth_send'"
            obj = params.find{|x| x.is_a?(Hash) && x['Authorization']}
            obj['Authorization'] = "Bearer #{@client_token}"
          end

The line throwing the exception is the RestClient.send just prior to the rescue clause, so I don't understand why the exception s not being handled there.

**Comment by artjomjuferov** [comment]
But why does it enter to endless loop? There is no recursion. Can't get it.

**Comment by jblauer60** [comment]
The loop is because my controller handles the exception by redirecting to /auth/spotify which regenerates the exception, and so on...

**Pull request merged**
