### PR TITLE
fix nonexistent variable in Playlist#add_tracks!

### PR DESCRIPTION
**Pull request by mitchellhenke**
this solves the same issue as #59, but sets snapshot_id in the same way that remove_tracks! does

### CODE REVIEW

**Comment by paulgonz6** [comment]
thanks mitchell, I was stuck on the same thing

**Comment by markusherzog** [comment]
Thanks, @mitchellhenke! Any idea how to rspec-test this method? Just asking out of curiosity.

**Comment by mitchellhenke** [comment]
@markusherzog I took a quick look initially, and it would likely require adding another VCR request.

**Comment by markusherzog** [comment]
@mitchellhenke yep, that's what I tried, but this request would need user credentials and there isn't any other VCR file that has them ...

**Comment by guilhermesad** [comment]
Thanks for this, `json` var was causing trouble as a leftover of https://github.com/guilhermesad/rspotify/commit/3d538bc0ac939ecbcf977889ab5a72a4ca66bee6. Using a single line for `@snapshot_id` is also cleaner.

@markusherzog this repo lacks tests for OAuth requests in general, which is definitely a point for improvement and I'm open to PRs on that. This issue is an example of something that could had been flagged on test phase.

**Comment by guilhermesad** [comment]
FYI I actually reverted `@snapshot_id` single assignment. Thing is that if `RSpotify.raw_response` is set to false `response` will already be parsed, so we shouldn't try to parse it again. Fix is in 56b6924c0652cf047f6dbf6d2adcae5f48048a14.

**Comment by mitchellhenke** [comment]
Thanks!

**Pull request merged**
